language: java

jdk:
  - oraclejdk7
  - openjdk6
  - openjdk7

install:
  - ./gradlew -PossrhUsername=none -PossrhPassword=none assemble

script:
  - ./gradlew -PossrhUsername=none -PossrhPassword=none check
